const types = {
    FRIENDS: { name: "Lovely Friends", code: "friends", color: "241, 99, 142" },
    ERASABLE: { name: "Erasable", code: "erasable", color: "147, 121, 153" },
}

const characters = {
    PANDA: { name: "Panda", statement: "Hug Me", image: "panda.jpg" },
    BEE: { name: "Bee", statement: "Bee Different", image: "bee.webp" },
    BUNNY_1: { name: "Bunny", statement: "Don't Worry Be Hoppy", image: "bunny.jpg" },
    DINO: { name: "Dino", statement: "Rooaarrr!", image: "dino.jpg" },
    HIPPO: { name: "Hippo", statement: "Hip Hippo Hooray", image: "hippo.jpg" },
    KITTY: { name: "Kitty", statement: "Be Curious", image: "kitty.jpg" },
    KOALA_1: { name: "Koala", statement: "Let Me Sleep", image: "koala.jpg" },
    LADYBUG: { name: "Ladybug", statement: "Get Lucky", image: "ladybug.jpg" },
    LION_1: { name: "Lion", statement: "Braveheart", image: "lion.jpg" },
    LLAMA: { name: "Llama", statement: "No Probllama", image: "llama.jpg" },
    MONSTER: { name: "Monster", statement: "Aaargh-dorable!", image: "monster.jpg" },
    SLOTH: { name: "Sloth", statement: "Take It Easy", image: "sloth.jpg" },
    TEDDY: { name: "Teddy", statement: "Dream Big", image: "bear.jpg" },
    TIGER: { name: "Tiger", statement: "Grrreat Adventures", image: "tiger.jpg" },
    UNICORN: { name: "Unicorn", statement: "Believe In Magic", image: "unicorn.jpg" },
    WHITE_BEAR: { name: "White Bear", statement: "I Love You Beary Much", image: "bearyinlove.png" },
    BROWN_BEAR: { name: "Brown Bear", statement: "I Love You More", image: "bearyinlove.png" },
    BUNNY_2: { name: "Bunny", statement: "Hoppy Vibes Only", image: "bunny2.png" },
    CHICK: { name: "Chick", statement: "Eggs-tra Happy", image: "chick.png" },
    SPIDER: { name: "Spider", statement: "Free Hugs", image: "spider.jpg" },
    GHOST: { name: "Ghost", statement: "Hey Boo!", image: "ghost.jpg" },
    BUTTERFLY: { name: "Butterfly", statement: "You Are Beautiful", image: "butterfly.jpg" },
    GIRAFFE: { name: "Giraffe", statement: "Head In The Clouds", image: "giraffe.jpg" },
    PENGUIN: { name: "Penguin", statement: "Always Cool", image: "penguin.jpg" },
    SHARK: { name: "Shark", statement: "Shark Attack", image: "shark.jpg" },
    CORGI: { name: "Corgi", statement: "Feelin’ Corgeous", image: "corgi.jpg" },
    COW: { name: "Cow", statement: "Always In The Moood", image: "cow.png" },
    PIGLET: { name: "Piglet", statement: "Rock ‘n’ Rolling", image: "piglet.png" },
    DONKEY: { name: "Donkey", statement: "Better Than A Unicorn", image: "donkey.png" },
    ROOSTER: { name: "Rooster", statement: "Rise and Shine", image: "rooster.png" },
    BIRD_YELLOW_BLUE_PURPLE: { name: "Bird", statement: "Life is better with you", notes: "Yellow, blue, and purple plumage", image: "bird1.png" },
    BIRD_ORANGE_GREEN_YELLOW: { name: "Bird", statement: "Always by your side", notes: "Orange, green, and yellow plumage", image: "bird2.png" },
    NUTCRACKER: { name: "Nutcracker", statement: "Nuts about Christmas", image: "nutcracker.png" },
    BALLERINA: { name: "Ballerina", statement: "Jingle Dance", image: "ballerina.png" },
    MOUSE: { name: "Mouse", statement: "Merry Squeakmas", image: "mouse.png" },
    ELF: { name: "Elf", statement: "Naughty or Nice", image: "elf.png" },
    REINDEER: { name: "Reindeer", statement: "Make a wish", image: "reindeer.png" },
    SANTA: { name: "Santa", statement: "Ho Ho Ho!", image: "santa.png" },
    TURTLE: { name: "Turtle", statement: "Free as the ocean", image: "turtle.png" },
    CLOWN_FISH: { name: "Clownfish", statement: "Never stop exploring", image: "clownfish.png" },
    SEAHORSE: { name: "Seahorse", statement: "Ride the waves", image: "seahorse.png" },
    ZOMBIE: { name: "Zombie", statement: "All you can eat", image: "zombie.png" },
    HALLOWEEN_CAT: { name: "Cat", statement: "The dark side of the moon", image: "halloweencat.png" },
    HALLOWEEN_SKELETON: { name: "Skeleton", statement: "Rock n Bone", image: "skull.png" },
    EASTER_BUNNY: { name: "Bunny", statement: "No-bunny like you", image: "bunny3.png" },
    EASTER_CHICK: { name: "Chick", statement: "Chick to chick", image: "chick2.png" },
    CAT_WITH_WOOL: { name: "Cat", statement: "I ♥ you", image: "tabbycat.png" },
    DOG: { name: "Dog", statement: "Forever together", image: "dog.png" },
    LION_2: { name: "Lion", statement: "The King", image: "lion.jpg" },
    ELEPHANT: { name: "Elephant", statement: "Elephantastic", image: "elephant.jpg" },
    KOALA_CHRISTMAS: { name: "Koala", statement: "Ho Ho Ho!", image: "christmaskoala.png" },
    BEAR_CHRISTMAS: { name: "Teddy Bear", statement: "Be Joyful", image: "christmasbear.png" },
    PANDA_CHRISTMAS: { name: "Panda", statement: "Warm Wishes", image: "christmaspanda.png" },
    BEAR: { name: "Train Conductor Bear", statement: "May Your Dreams Come True", image: "trainconductor.png" },
    YETI: { name: "Yeti", statement: "Are you yeti for Christmas", image: "yeti.jpg" },
    FRANKENSTEINS_MONSTER: { name: "Frankenstein's Monster", statement: "Peek-a-boo", image: "frank.jpg" },
    MUMMY: { name: "Mummy", statement: "Groowrrr", image: "mummy.png" },
    PUMPKIN: { name: "Pumpkin", statement: "Trick or treat", image: "pumpkin.jpg" },
    BAT: { name: "Bat", statement: "Too cute to spook", image: "bat.png" },
    WITCH: { name: "Witch", statement: "Hocus pocus", image: "witch.png" },
    VAMPIRE: { name: "Vampire", statement: "Fab-boo-lous", image: "vampire.png" },
    ASTRONAUT: { name: "Astronaut", statement: "Space Explorer", image: "astronaut.jpg" },
    FLORA: { name: "Flora", statement: "Bloom your own way", image: "flora.jpg" },
    KOALA_2: { name: "Koala", statement: "Take it easy", image: "koala.jpg" },
    PIG: { name: "Pig", statement: "Think pink", image: "pig.jpg" },
    SHARK_GRUMPY: { name: "Shark", statement: "Shark attack", image: "grumpyshark.png" },
    PENGUIN_CHRISTMAS: { name: "Penguin", statement: "Merry & Brrright", image: "penguin.jpg" },
    FOX_CHRISTMAS: { name: "Fox", statement: "Foxtastic Holidays", image: "fox.jpg" },
    POLAR_BEAR_CHRISTMAS: { name: "Polar Bear", statement: "Greetings from the North Pole", image: "polarbear.jpg" },
}

const characterGroups = {
    PANDA: { "name": "Panda", characters: [characters.PANDA, characters.PANDA_CHRISTMAS] },
    BEE: { "name": "Bee", characters: [characters.BEE] },
    BUNNY: { "name": "Bunny", characters: [characters.BUNNY_1, characters.BUNNY_2, characters.EASTER_BUNNY] },
    DINO: { "name": "Dino", characters: [characters.DINO] },
    HIPPO: { "name": "Hippo", characters: [characters.HIPPO] },
    KITTY: { "name": "Kitty", characters: [characters.KITTY, characters.HALLOWEEN_CAT, characters.CAT_WITH_WOOL] },
    KOALA: { "name": "Koala", characters: [characters.KOALA_1, characters.KOALA_2, characters.KOALA_CHRISTMAS] },
    LADYBUG: { "name": "Ladybug", characters: [characters.LADYBUG] },
    LION: { "name": "Lion", characters: [characters.LION_1, characters.LION_2] },
    LLAMA: { "name": "Llama", characters: [characters.LLAMA] },
    MONSTER: { "name": "Monster", characters: [characters.MONSTER] },
    SLOTH: { "name": "Sloth", characters: [characters.SLOTH] },
    TIGER: { "name": "Tiger", characters: [characters.TIGER] },
    UNICORN: { "name": "Unicorn", characters: [characters.UNICORN] },
    BEAR: { "name": "Bear", characters: [characters.TEDDY, characters.WHITE_BEAR, characters.BROWN_BEAR, characters.BEAR, characters.BEAR_CHRISTMAS, characters.POLAR_BEAR_CHRISTMAS] },
    CHICK: { "name": "Chick", characters: [characters.CHICK, characters.EASTER_CHICK] },
    SPIDER: { "name": "Spider", characters: [characters.SPIDER] },
    GHOST: { "name": "Ghost", characters: [characters.GHOST] },
    BUTTERFLY: { "name": "Butterfly", characters: [characters.BUTTERFLY] },
    GIRAFFE: { "name": "Giraffe", characters: [characters.GIRAFFE] },
    PENGUIN: { "name": "Penguin", characters: [characters.PENGUIN] },
    SHARK: { "name": "Shark", characters: [characters.SHARK, characters.SHARK_GRUMPY] },
    CORGI: { "name": "Corgi", characters: [characters.CORGI] },
    COW: { "name": "Cow", characters: [characters.COW] },
    PIGLET: { "name": "Pig", characters: [characters.PIG, characters.PIGLET] },
    DONKEY: { "name": "Donkey", characters: [characters.DONKEY] },
    ROOSTER: { "name": "Rooster", characters: [characters.ROOSTER] },
    BIRD: { "name": "Bird", characters: [characters.BIRD_YELLOW_BLUE_PURPLE, characters.BIRD_ORANGE_GREEN_YELLOW] },
    NUTCRACKER: { "name": "Nutcracker", characters: [characters.NUTCRACKER] },
    BALLERINA: { "name": "Ballerina", characters: [characters.BALLERINA] },
    MOUSE: { "name": "Mouse", characters: [characters.MOUSE] },
    ELF: { "name": "Elf", characters: [characters.ELF] },
    REINDEER: { "name": "Reindeer", characters: [characters.REINDEER] },
    SANTA: { "name": "Santa", characters: [characters.SANTA] },
    TURTLE: { "name": "Turtle", characters: [characters.TURTLE] },
    CLOWN_FISH: { "name": "Clownfish", characters: [characters.CLOWN_FISH] },
    SEAHORSE: { "name": "Seahorse", characters: [characters.SEAHORSE] },
    ZOMBIE: { "name": "Zombie", characters: [characters.ZOMBIE] },
    HALLOWEEN_SKELETON: { "name": "Skeleton", characters: [characters.HALLOWEEN_SKELETON] },
    DOG: { "name": "Dog", characters: [characters.DOG] },
    ELEPHANT: { "name": "Elephant", characters: [characters.ELEPHANT] },
    YETI: { "name": "Yeti", characters: [characters.YETI] },
    FRANKENSTEINS_MONSTER: { "name": "Frankenstein's Monster", characters: [characters.FRANKENSTEINS_MONSTER] },
    MUMMY: { "name": "Mummy", characters: [characters.MUMMY] },
    PUMPKIN: { "name": "Pumpkin", characters: [characters.PUMPKIN] },
    BAT: { "name": "Bat", characters: [characters.BAT] },
    WITCH: { "name": "Witch", characters: [characters.WITCH] },
    VAMPIRE: { "name": "Vampire", characters: [characters.VAMPIRE] },
    ASTRONAUT: { "name": "Astronaut", characters: [characters.ASTRONAUT] },
    FLORA: { "name": "Flora", characters: [characters.FLORA] },
    FOX_CHRISTMAS: { "name": "Fox", characters: [characters.FOX_CHRISTMAS] },
}

const colors = {
    BLACK: { name: "Black", color: "#000000" },
    PINK: { name: "Pink", color: "#ED8BC5" },
    PURPLE: { name: "Purple", color: "#8B3BB4" },
    BLUE: { name: "Blue", color: "#194D9B" },
    GREEN: { name: "Green", color: "#4BA23F" },
    RED: { name: "Red", color: "#D2021D" },
    TURQUOISE: { name: "Turquoise", color: "#C5ECEC" },
    ORANGE: { name: "Orange", color: "#EA6C2C" },
    SKY_BLUE: { name: "Sky Blue", color: "#87CEEB" },
    NEON_GREEN: { name: "Neon Green", color: "#39FF14" },
    NEON_PINK: { name: "Neon Pink", color: "#FF1493" },
    METALLIC_PINK: { name: "Metallic Pink", color: "#E6A8D7", metallic: true },
    METALLIC_PURPLE: { name: "Metallic Purple", color: "#9966CC", metallic: true },
}

const events = {
    VALENTINES: { name: "Valentines" },
    HALLOWEEN: { name: "Halloween" },
    EASTER: { name: "Easter" },
    CHRISTMAS: { name: "Christmas" },
}

const multipacks = {
    BEARY_IN_LOVE: { name: "Beary in Love", event: events.VALENTINES, year: 2025 },
    HOPPY_EASTER_1: { name: "Hoppy Easter", event: events.EASTER, year: 2026 },
    HOPPY_EASTER_2: { name: "Hoppy Easter", event: events.EASTER, year: 2025 },
    BETTER_TOGETHER_1: { name: "Better Together", event: events.VALENTINES, year: 2026 },
    BETTER_TOGETHER_2: { name: "Better Together", event: events.VALENTINES, year: 2024 },
    NUTCRACKER: { name: "The Nutcracker", event: events.CHRISTMAS, year: 2025 },
    NAUGHTY_OR_NICE: { name: "Naughty or Nice", event: events.CHRISTMAS, year: 2024 },
    BOO_CREW_1: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2025 },
    BOO_CREW_2: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2024 },
    BOO_CREW_3: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2023 },
    FARM: { name: "Farm Sweet Farm", event: null, year: 2025 },
    UNDER_THE_SEA: { name: "Under the Sea", event: null, year: 2024, discontinued: 2025 },
    WILD_SAVANNAH: { name: "Wild Savannah", event: null, year: 2023, discontinued: 2025 },
}

const pens = [
    // Lovely Friends
    { character: characters.PANDA, color: colors.BLACK, type: types.FRIENDS },
    { character: characters.BEE, color: colors.BLACK, type: types.FRIENDS },
    { character: characters.BUNNY_1, color: colors.PURPLE, type: types.FRIENDS },
    { character: characters.DINO, color: colors.NEON_GREEN, type: types.FRIENDS },
    { character: characters.HIPPO, color: colors.BLUE, type: types.FRIENDS },
    { character: characters.KITTY, color: colors.PINK, type: types.FRIENDS },
    { character: characters.KOALA_1, color: colors.GREEN, type: types.FRIENDS },
    { character: characters.LADYBUG, color: colors.RED, type: types.FRIENDS },
    { character: characters.LLAMA, color: colors.TURQUOISE, type: types.FRIENDS },
    { character: characters.MONSTER, color: colors.BLUE, type: types.FRIENDS },
    { character: characters.SLOTH, color: colors.BLUE, type: types.FRIENDS },
    { character: characters.TEDDY, color: colors.RED, type: types.FRIENDS },
    { character: characters.TIGER, color: colors.ORANGE, type: types.FRIENDS },
    { character: characters.UNICORN, color: colors.NEON_PINK, type: types.FRIENDS },

    // 2026
    { character: characters.BUNNY_2, color: colors.METALLIC_PINK, type: types.FRIENDS, multipack: multipacks.HOPPY_EASTER_1 },
    { character: characters.CHICK, color: colors.METALLIC_PURPLE, type: types.FRIENDS, multipack: multipacks.HOPPY_EASTER_1 },

    // 2025
    { character: characters.WHITE_BEAR, color: colors.PURPLE, type: types.FRIENDS, multipack: multipacks.BEARY_IN_LOVE },
    { character: characters.BROWN_BEAR, color: colors.SKY_BLUE, type: types.FRIENDS, multipack: multipacks.BEARY_IN_LOVE },
    { character: characters.SPIDER, color: colors.NEON_GREEN, type: types.FRIENDS, event: events.HALLOWEEN, year: 2025 },

    // 2024
    { character: characters.GHOST, color: colors.NEON_GREEN, type: types.FRIENDS, event: events.HALLOWEEN, year: 2024 },

    // Erasable
    { character: characters.PANDA, color: colors.BLACK, type: types.ERASABLE },
    { character: characters.BEE, color: colors.BLACK, type: types.ERASABLE, year: 2024 },
    { character: characters.BUNNY_1, color: colors.PURPLE, type: types.ERASABLE, year: 2022 },
    { character: characters.DINO, color: colors.GREEN, type: types.ERASABLE },
    { character: characters.HIPPO, color: colors.BLUE, type: types.ERASABLE, year: 2024 },
    { character: characters.KITTY, color: colors.BLACK, type: types.ERASABLE },
    { character: characters.LADYBUG, color: colors.RED, type: types.ERASABLE, year: 2026 },
    { character: characters.LLAMA, color: colors.BLUE, type: types.ERASABLE },
    { character: characters.MONSTER, color: colors.BLUE, type: types.ERASABLE, year: 2025 },
    { character: characters.TEDDY, color: colors.RED, type: types.ERASABLE, year: 2023 },
    { character: characters.TIGER, color: colors.ORANGE, type: types.ERASABLE, year: 2025 },
    { character: characters.UNICORN, color: colors.PINK, type: types.ERASABLE, year: 2022 },
    { character: characters.BUTTERFLY, color: colors.PINK, type: types.ERASABLE, year: 2025 },
    { character: characters.PENGUIN, color: colors.TURQUOISE, type: types.ERASABLE, year: 2024 },
    { character: characters.SHARK, color: colors.BLUE, type: types.ERASABLE, year: 2023 },
    { character: characters.CORGI, color: colors.BLACK, type: types.ERASABLE, year: 2023 },

    // 2026
    { character: characters.BIRD_YELLOW_BLUE_PURPLE, color: colors.TURQUOISE, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_1 },
    { character: characters.BIRD_ORANGE_GREEN_YELLOW, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_1 },

    // 2025
    { character: characters.NUTCRACKER, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.NUTCRACKER },
    { character: characters.BALLERINA, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.NUTCRACKER },
    { character: characters.MOUSE, color: colors.RED, type: types.ERASABLE, multipack: multipacks.NUTCRACKER },
    { character: characters.BEAR, color: colors.RED, type: types.ERASABLE, event: events.CHRISTMAS, year: 2025, notes: "Advent calendar" },
    { character: characters.ZOMBIE, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1 },
    { character: characters.HALLOWEEN_CAT, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1 },
    { character: characters.HALLOWEEN_SKELETON, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1 },
    { character: characters.COW, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.FARM },
    { character: characters.PIGLET, color: colors.PINK, type: types.ERASABLE, multipack: multipacks.FARM },
    { character: characters.DONKEY, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.FARM },
    { character: characters.ROOSTER, color: colors.RED, type: types.ERASABLE, multipack: multipacks.FARM },
    { character: characters.EASTER_BUNNY, color: colors.PINK, type: types.ERASABLE, multipack: multipacks.HOPPY_EASTER_2 },
    { character: characters.EASTER_CHICK, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.HOPPY_EASTER_2 },

    // 2024
    { character: characters.ELF, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE },
    { character: characters.REINDEER, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE },
    { character: characters.SANTA, color: colors.RED, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE },
    { character: characters.SANTA, color: colors.BLACK, type: types.ERASABLE, event: events.CHRISTMAS, year: 2024, notes: "Blue pen, available separately to the Naughty or Nice multipack" },
    { character: characters.YETI, color: colors.BLUE, type: types.ERASABLE, event: events.CHRISTMAS, year: 2024, notes: "Advent calendar" },
    { character: characters.BAT, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2 },
    { character: characters.WITCH, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2 },
    { character: characters.VAMPIRE, color: colors.RED, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2 },
    { character: characters.TURTLE, color: colors.TURQUOISE, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA },
    { character: characters.CLOWN_FISH, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA },
    { character: characters.SEAHORSE, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA },
    { character: characters.CAT_WITH_WOOL, color: colors.RED, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_2 },
    { character: characters.DOG, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_2 },

    // 2023
    { character: characters.PENGUIN_CHRISTMAS, color: colors.BLUE, type: types.ERASABLE, event: events.CHRISTMAS, year: 2023 },
    { character: characters.FOX_CHRISTMAS, color: colors.GREEN, type: types.ERASABLE, event: events.CHRISTMAS, year: 2023 },
    { character: characters.POLAR_BEAR_CHRISTMAS, color: colors.RED, type: types.ERASABLE, event: events.CHRISTMAS, year: 2023 },
    { character: characters.FRANKENSTEINS_MONSTER, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3 },
    { character: characters.MUMMY, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3 },
    { character: characters.PUMPKIN, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3 },
    { character: characters.LION_2, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH },
    { character: characters.ELEPHANT, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH },
    { character: characters.GIRAFFE, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH, individual: true },

    // 2022
    { character: characters.KOALA_CHRISTMAS, color: colors.BLUE, type: types.ERASABLE, event: events.CHRISTMAS, year: 2022 },
    { character: characters.BEAR_CHRISTMAS, color: colors.RED, type: types.ERASABLE, event: events.CHRISTMAS, year: 2022 },
    { character: characters.PANDA_CHRISTMAS, color: colors.BLACK, type: types.ERASABLE, event: events.CHRISTMAS, year: 2022 },

    // Discontinued
    { character: characters.LION_1, color: colors.BLACK, type: types.FRIENDS, year: 2023, discontinued: 2025 },
    { character: characters.ASTRONAUT, color: colors.BLACK, type: types.ERASABLE, discontinued: 2024 },
    { character: characters.FLORA, color: colors.PINK, type: types.ERASABLE, discontinued: 2024 },
    { character: characters.PIG, color: colors.PINK, type: types.ERASABLE, discontinued: 2024 },
    { character: characters.PANDA, color: colors.BLACK, type: types.ERASABLE, discontinued: 2024, notes: "Plain white pen" },
    { character: characters.KOALA_2, color: colors.RED, type: types.ERASABLE, discontinued: 2023 },
    { character: characters.SHARK_GRUMPY, color: colors.BLUE, type: types.ERASABLE, discontinued: 2023 },
    { character: characters.UNICORN, color: colors.BLACK, type: types.ERASABLE, discontinued: 2022, notes: "Plain white pen" },
]