const types = {
    FRIENDS: { name: "Gel Pens", code: "friends", color: "241, 99, 142" },
    ERASABLE: { name: "Erasable", code: "erasable", color: "147, 121, 153" },
}

const characters = {
    PANDA: { name: "Panda", statement: "Hug Me", image: "panda.jpg" },
    BEE: { name: "Bee", statement: "Bee Different", image: "bee.webp" },
    BUNNY_1: { name: "Bunny", statement: "Don't Worry Be Hoppy", image: "bunny.jpg" },
    DINO: { name: "Dino", statement: "Rooaarrr!", image: "dino.jpg" },
    HIPPO: { name: "Hippo", statement: "Hip Hippo Hooray", image: "hippo.jpg" },
    KITTY: { name: "Kitty", statement: "Be Curious", image: "kitty.jpg" },
    KITTY_2: { name: "Kitty", statement: "Meow", image: "kitty.jpg" },
    KOALA_1: { name: "Koala", statement: "Let Me Sleep", image: "koala.jpg" },
    LADYBUG: { name: "Ladybug", statement: "Get Lucky", image: "ladybug.jpg" },
    LION_1: { name: "Lion", statement: "Braveheart", image: "lion.jpg" },
    LLAMA: { name: "Llama", statement: "No Probllama", image: "llama.jpg" },
    MONSTER: { name: "Monster", statement: "Aaargh-dorable!", image: "monster.jpg" },
    SLOTH: { name: "Sloth", statement: "Take It Easy", image: "sloth.jpg" },
    TEDDY: { name: "Teddy", statement: "Dream Big", image: "bear.jpg" },
    TIGER: { name: "Tiger", statement: "Grrreat Adventures", image: "tiger.jpg" },
    UNICORN: { name: "Unicorn", statement: "Believe In Magic", image: "unicorn.jpg" },
    WHITE_BEAR: { name: "White Bear", statement: "I Love You Beary Much", image: "bearyinlove.png" },
    BROWN_BEAR: { name: "Brown Bear", statement: "I Love You More", image: "bearyinlove.png" },
    BUNNY_2: { name: "Bunny", statement: "Hoppy Vibes Only", image: "bunny2.png" },
    CHICK: { name: "Chick", statement: "Eggs-tra Happy", image: "chick.png" },
    SPIDER: { name: "Spider", statement: "Free Hugs", image: "spider.jpg" },
    GHOST: { name: "Ghost", statement: "Hey Boo!", image: "ghost.jpg" },
    BUTTERFLY: { name: "Butterfly", statement: "You Are Beautiful", image: "butterfly.jpg" },
    GIRAFFE: { name: "Giraffe", statement: "Head In The Clouds", image: "giraffe.jpg" },
    PENGUIN: { name: "Penguin", statement: "Always Cool", image: "penguin.jpg" },
    SHARK: { name: "Shark", statement: "Shark Attack", image: "shark.jpg" },
    CORGI: { name: "Corgi", statement: "Feelin’ Corgeous", image: "corgi.jpg" },
    COW: { name: "Cow", statement: "Always In The Moood", image: "cow.png" },
    PIGLET: { name: "Piglet", statement: "Rock ‘n’ Rolling", image: "piglet.png" },
    DONKEY: { name: "Donkey", statement: "Better Than A Unicorn", image: "donkey.png" },
    ROOSTER: { name: "Rooster", statement: "Rise and Shine", image: "rooster.png" },
    BIRD_YELLOW_BLUE_PURPLE: { name: "Bird", statement: "Life is better with you", notes: "Yellow, blue, and purple plumage", image: "bird1.png" },
    BIRD_ORANGE_GREEN_YELLOW: { name: "Bird", statement: "Always by your side", notes: "Orange, green, and yellow plumage", image: "bird2.png" },
    NUTCRACKER: { name: "Nutcracker", statement: "Nuts about Christmas", image: "nutcracker.png" },
    BALLERINA: { name: "Ballerina", statement: "Jingle Dance", image: "ballerina.png" },
    MOUSE: { name: "Mouse", statement: "Merry Squeakmas", image: "mouse.png" },
    ELF: { name: "Elf", statement: "Naughty or Nice", image: "elf.png" },
    REINDEER: { name: "Reindeer", statement: "Make a wish", image: "reindeer.png" },
    SANTA: { name: "Santa", statement: "Ho Ho Ho!", image: "santa.png" },
    TURTLE: { name: "Turtle", statement: "Free as the ocean", image: "turtle2.png" },
    CLOWN_FISH: { name: "Clownfish", statement: "Never stop exploring", image: "clownfish2.png" },
    SEAHORSE: { name: "Seahorse", statement: "Ride the waves", image: "seahorse2.png" },
    ZOMBIE: { name: "Zombie", statement: "All you can eat", image: "zombie.png" },
    HALLOWEEN_CAT: { name: "Cat", statement: "The dark side of the moon", image: "halloweencat.png" },
    HALLOWEEN_SKELETON: { name: "Skeleton", statement: "Rock n Bone", image: "skull.png" },
    EASTER_BUNNY: { name: "Bunny", statement: "No-bunny like you", image: "bunny3.png" },
    EASTER_CHICK: { name: "Chick", statement: "Chick to chick", image: "chick2.png" },
    CAT_WITH_WOOL: { name: "Cat", statement: "I ♥ you", image: "tabbycat.png" },
    DOG: { name: "Dog", statement: "Forever together", image: "dog.png" },
    LION_2: { name: "Lion", statement: "The King", image: "lion.jpg" },
    ELEPHANT: { name: "Elephant", statement: "Elephantastic", image: "elephant.jpg" },
    KOALA_CHRISTMAS: { name: "Koala", statement: "Ho Ho Ho!", image: "christmaskoala.png" },
    BEAR_CHRISTMAS: { name: "Teddy Bear", statement: "Be Joyful", image: "christmasbear.png" },
    PANDA_CHRISTMAS: { name: "Panda", statement: "Warm Wishes", image: "christmaspanda.png" },
    BEAR: { name: "Train Conductor Bear", statement: "May Your Dreams Come True", image: "trainconductor.png" },
    YETI: { name: "Yeti", statement: "Are you yeti for Christmas", image: "yeti.jpg" },
    FRANKENSTEINS_MONSTER: { name: "Frankenstein's Monster", statement: "Peek-a-boo", image: "frank.jpg" },
    MUMMY: { name: "Mummy", statement: "Groowrrr", image: "mummy.png" },
    PUMPKIN: { name: "Pumpkin", statement: "Trick or treat", image: "pumpkin.jpg" },
    BAT: { name: "Bat", statement: "Too cute to spook", image: "bat.png" },
    BAT2: { name: "Bat", statement: "Too cute to spook", image: "bat2.png" },
    WITCH: { name: "Witch", statement: "Hocus pocus", image: "witch.png" },
    VAMPIRE: { name: "Vampire", statement: "Fab-boo-lous", image: "vampire.png" },
    ASTRONAUT: { name: "Astronaut", statement: "Space Explorer", image: "astronaut.jpg" },
    FLORA: { name: "Flora", statement: "Bloom your own way", image: "flora.jpg" },
    KOALA_2: { name: "Koala", statement: "Take it easy", image: "koala.jpg" },
    PIG: { name: "Pig", statement: "Think pink", image: "pig.jpg" },
    SHARK_GRUMPY: { name: "Shark", statement: "Shark attack", image: "grumpyshark.png" },
    PENGUIN_CHRISTMAS: { name: "Penguin", statement: "Merry & Brrright", image: "penguin.jpg" },
    FOX_CHRISTMAS: { name: "Fox", statement: "Foxtastic Holidays", image: "fox.jpg" },
    POLAR_BEAR_CHRISTMAS: { name: "Polar Bear", statement: "Greetings from the North Pole", image: "polarbear.jpg" },
    GOLDEN_RETRIEVER: { name: "Golden Retriever", statement: "Fur-ever Friends", image: "retriever.png" },
    BULLDOG: { name: "Bulldog", statement: "Big Nap Boss", image: "bulldog.png" },
    POODLE: { name: "Poodle", statement: "Cute? ... Try iconic!", image: "poodle.png" },
}

const characterGroups = {
    PANDA: { "name": "Panda", characters: [characters.PANDA, characters.PANDA_CHRISTMAS] },
    BEE: { "name": "Bee", characters: [characters.BEE] },
    BUNNY: { "name": "Bunny", characters: [characters.BUNNY_1, characters.BUNNY_2, characters.EASTER_BUNNY] },
    DINO: { "name": "Dino", characters: [characters.DINO] },
    HIPPO: { "name": "Hippo", characters: [characters.HIPPO] },
    KITTY: { "name": "Kitty", characters: [characters.KITTY, characters.KITTY_2, characters.HALLOWEEN_CAT, characters.CAT_WITH_WOOL] },
    KOALA: { "name": "Koala", characters: [characters.KOALA_1, characters.KOALA_2, characters.KOALA_CHRISTMAS] },
    LADYBUG: { "name": "Ladybug", characters: [characters.LADYBUG] },
    LION: { "name": "Lion", characters: [characters.LION_1, characters.LION_2] },
    LLAMA: { "name": "Llama", characters: [characters.LLAMA] },
    MONSTER: { "name": "Monster", characters: [characters.MONSTER] },
    SLOTH: { "name": "Sloth", characters: [characters.SLOTH] },
    TIGER: { "name": "Tiger", characters: [characters.TIGER] },
    UNICORN: { "name": "Unicorn", characters: [characters.UNICORN] },
    BEAR: { "name": "Bear", characters: [characters.TEDDY, characters.WHITE_BEAR, characters.BROWN_BEAR, characters.BEAR, characters.BEAR_CHRISTMAS, characters.POLAR_BEAR_CHRISTMAS] },
    CHICK: { "name": "Chick", characters: [characters.CHICK, characters.EASTER_CHICK] },
    SPIDER: { "name": "Spider", characters: [characters.SPIDER] },
    GHOST: { "name": "Ghost", characters: [characters.GHOST] },
    BUTTERFLY: { "name": "Butterfly", characters: [characters.BUTTERFLY] },
    GIRAFFE: { "name": "Giraffe", characters: [characters.GIRAFFE] },
    PENGUIN: { "name": "Penguin", characters: [characters.PENGUIN] },
    SHARK: { "name": "Shark", characters: [characters.SHARK, characters.SHARK_GRUMPY] },
    CORGI: { "name": "Corgi", characters: [characters.CORGI] },
    COW: { "name": "Cow", characters: [characters.COW] },
    PIGLET: { "name": "Pig", characters: [characters.PIG, characters.PIGLET] },
    DONKEY: { "name": "Donkey", characters: [characters.DONKEY] },
    ROOSTER: { "name": "Rooster", characters: [characters.ROOSTER] },
    BIRD: { "name": "Bird", characters: [characters.BIRD_YELLOW_BLUE_PURPLE, characters.BIRD_ORANGE_GREEN_YELLOW] },
    NUTCRACKER: { "name": "Nutcracker", characters: [characters.NUTCRACKER] },
    BALLERINA: { "name": "Ballerina", characters: [characters.BALLERINA] },
    MOUSE: { "name": "Mouse", characters: [characters.MOUSE] },
    ELF: { "name": "Elf", characters: [characters.ELF] },
    REINDEER: { "name": "Reindeer", characters: [characters.REINDEER] },
    SANTA: { "name": "Santa", characters: [characters.SANTA] },
    TURTLE: { "name": "Turtle", characters: [characters.TURTLE] },
    CLOWN_FISH: { "name": "Clownfish", characters: [characters.CLOWN_FISH] },
    SEAHORSE: { "name": "Seahorse", characters: [characters.SEAHORSE] },
    ZOMBIE: { "name": "Zombie", characters: [characters.ZOMBIE] },
    HALLOWEEN_SKELETON: { "name": "Skeleton", characters: [characters.HALLOWEEN_SKELETON] },
    DOG: { "name": "Dog", characters: [characters.DOG, characters.CORGI, characters.GOLDEN_RETRIEVER, characters.BULLDOG, characters.POODLE] },
    ELEPHANT: { "name": "Elephant", characters: [characters.ELEPHANT] },
    YETI: { "name": "Yeti", characters: [characters.YETI] },
    FRANKENSTEINS_MONSTER: { "name": "Frankenstein's Monster", characters: [characters.FRANKENSTEINS_MONSTER] },
    MUMMY: { "name": "Mummy", characters: [characters.MUMMY] },
    PUMPKIN: { "name": "Pumpkin", characters: [characters.PUMPKIN] },
    BAT: { "name": "Bat", characters: [characters.BAT, characters.BAT2] },
    WITCH: { "name": "Witch", characters: [characters.WITCH] },
    VAMPIRE: { "name": "Vampire", characters: [characters.VAMPIRE] },
    ASTRONAUT: { "name": "Astronaut", characters: [characters.ASTRONAUT] },
    FLORA: { "name": "Flora", characters: [characters.FLORA] },
    FOX_CHRISTMAS: { "name": "Fox", characters: [characters.FOX_CHRISTMAS] },
}

const colors = {
    BLACK: { name: "Black", color: "#000000" },
    PINK: { name: "Pink", color: "#ED8BC5" },
    PURPLE: { name: "Purple", color: "#8B3BB4" },
    BLUE: { name: "Blue", color: "#194D9B" },
    GREEN: { name: "Green", color: "#4BA23F" },
    RED: { name: "Red", color: "#D2021D" },
    ORANGE: { name: "Orange", color: "#EA6C2C" },
    SKY_BLUE: { name: "Sky Blue", color: "#87CEEB" },
    NEON_GREEN: { name: "Neon Green", color: "#39FF14" },
    NEON_PINK: { name: "Neon Pink", color: "#FF1493" },
    METALLIC_PINK: { name: "Metallic Pink", color: "#E6A8D7", metallic: true },
    METALLIC_PURPLE: { name: "Metallic Purple", color: "#9966CC", metallic: true },
}

const events = {
    VALENTINES: { name: "Valentines" },
    HALLOWEEN: { name: "Halloween" },
    EASTER: { name: "Easter" },
    CHRISTMAS: { name: "Christmas" },
}

const multipacks = {
    BEARY_IN_LOVE: { name: "Beary in Love", event: events.VALENTINES, year: 2025, legamiId: "CPPSET1" },
    HOPPY_EASTER_1: { name: "Hoppy Easter", event: events.EASTER, year: 2026, legamiId: "CPPSET2" },

    ORIGINAL: { name: "Original Collection", event: null, year: 2023, discontinued: 2024, legamiId: "EPSET0001" },
    CHRISTMAS_2022: { name: "Christmas 2022", event: events.CHRISTMAS, year: 2022, legamiId: "EPSET0002" },
    WILD_SAVANNAH: { name: "Wild Savannah", event: null, year: 2023, discontinued: 2025, legamiId: "EPSET0003" },
    CHRISTMAS_2023: { name: "It's Christmas Time", event: events.CHRISTMAS, year: 2023, legamiId: "EPSET0004" },
    BOO_CREW_3: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2023, legamiId: "EPSET0005" },
    BETTER_TOGETHER_2: { name: "Better Together", event: events.VALENTINES, year: 2024, legamiId: "EPSET0006" },
    UNDER_THE_SEA: { name: "Under the Sea", event: null, year: 2024, discontinued: 2025, legamiId: "EPSET0007" },
    BOO_CREW_2: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2024, legamiId: "EPSET0008" },
    NAUGHTY_OR_NICE: { name: "Naughty or Nice", event: events.CHRISTMAS, year: 2024, legamiId: "EPSET0009" },
    HOPPY_EASTER_2: { name: "Hoppy Easter", event: events.EASTER, year: 2025, legamiId: "EPSET0010" },
    FARM: { name: "Farm Sweet Farm", event: null, year: 2025, legamiId: ["EPSET0011", "EPSET0016"] },

    BOO_CREW_1: { name: "The Boo Crew", event: events.HALLOWEEN, year: 2025, legamiId: "EPSET0013" },
    NUTCRACKER: { name: "The Nutcracker", event: events.CHRISTMAS, year: 2025, legamiId: "EPSET0014" },
    BETTER_TOGETHER_1: { name: "Better Together", event: events.VALENTINES, year: 2026, legamiId: "EPSET0015" },
    FUREVER_FRIENDS: { name: "Fur-ever Friends", event: null, year: 2026, legamiId: "EPSET0017" },
}

const pens = [
    // Lovely Friends
    { id: "F001", character: characters.PANDA, color: colors.BLACK, type: types.FRIENDS, image: "friends-panda.webp", legamiId: "CPP0016" },
    { id: "F002", character: characters.BEE, color: colors.BLACK, type: types.FRIENDS, image: "friends-bee.webp", legamiId: "CPP0012" },
    { id: "F003", character: characters.BUNNY_1, color: colors.PURPLE, type: types.FRIENDS, image: "friends-bunny.webp", legamiId: "CPP0009" },
    { id: "F004", character: characters.DINO, color: colors.NEON_GREEN, type: types.FRIENDS, image: "friends-dino.webp", legamiId: "CPP0007" },
    { id: "F005", character: characters.HIPPO, color: colors.BLUE, type: types.FRIENDS, image: "friends-hippo.webp", legamiId: "CPP0015" },
    { id: "F006", character: characters.KITTY, color: colors.PINK, type: types.FRIENDS, image: "friends-kitty.webp", legamiId: "CPP0002" },
    { id: "F007", character: characters.KOALA_1, color: colors.GREEN, type: types.FRIENDS, image: "friends-koala.webp", legamiId: "CPP0004" },
    { id: "F008", character: characters.LADYBUG, color: colors.RED, type: types.FRIENDS, year: 2026, image: "friends-ladybug.webp", legamiId: "CPP0027" },
    { id: "F009", character: characters.LION_1, color: colors.BLACK, type: types.FRIENDS, year: 2023, image: "friends-lion.webp", legamiId: "CPP0013" },
    { id: "F010", character: characters.LLAMA, color: colors.SKY_BLUE, type: types.FRIENDS, image: "friends-llama.webp", legamiId: "CPP0010" },
    { id: "F011", character: characters.MONSTER, color: colors.BLUE, type: types.FRIENDS, image: "friends-monster.webp", legamiId: "CPP0014" },
    { id: "F012", character: characters.SLOTH, color: colors.BLUE, type: types.FRIENDS, image: "friends-sloth.webp", legamiId: "CPP0005" },
    { id: "F013", character: characters.TEDDY, color: colors.RED, type: types.FRIENDS, image: "friends-teddy.webp", legamiId: "CPP0003" },
    { id: "F014", character: characters.TIGER, color: colors.ORANGE, type: types.FRIENDS, image: "friends-tiger.webp", legamiId: "CPP0008" },
    { id: "F015", character: characters.UNICORN, color: colors.NEON_PINK, type: types.FRIENDS, image: "friends-unicorn.webp", legamiId: "CPP0006" },
    { id: "F022", character: characters.KITTY_2, color: colors.PINK, type: types.FRIENDS, image: "friends-kitty-meow.png", year: 2026, legamiId: "CPP0017", notes: "Pen barrel fades from pink to purple" },
    { id: "F023", character: characters.LLAMA, color: colors.SKY_BLUE, type: types.FRIENDS, image: "friends-llama-patterned.webp", year: 2026, notes: "Pen barrel fully patterned" },

    // 2026
    { id: "F016", character: characters.BUNNY_2, color: colors.METALLIC_PINK, type: types.FRIENDS, multipack: multipacks.HOPPY_EASTER_1, image: "friends-bunny2.webp", legamiId: "CPP0028" },
    { id: "F017", character: characters.CHICK, color: colors.METALLIC_PURPLE, type: types.FRIENDS, multipack: multipacks.HOPPY_EASTER_1, image: "friends-chick.webp", legamiId: "CPP0029" },

    // 2025
    { id: "F018", character: characters.WHITE_BEAR, color: colors.PURPLE, type: types.FRIENDS, multipack: multipacks.BEARY_IN_LOVE, image: "friends-whitebear.webp" },
    { id: "F019", character: characters.BROWN_BEAR, color: colors.SKY_BLUE, type: types.FRIENDS, multipack: multipacks.BEARY_IN_LOVE, image: "friends-brownbear.webp" },
    { id: "F020", character: characters.SPIDER, color: colors.NEON_GREEN, type: types.FRIENDS, event: events.HALLOWEEN, year: 2025, image: "friends-spider.webp" },

    // 2024
    { id: "F021", character: characters.GHOST, color: colors.NEON_GREEN, type: types.FRIENDS, event: events.HALLOWEEN, year: 2024, image: "friends-ghoost.jpg" },

    // Erasable
    { id: "E001", character: characters.PANDA, color: colors.BLACK, type: types.ERASABLE, image: "erasable-panda.webp", legamiId: "EP0001" },
    { id: "E002", character: characters.BEE, color: colors.BLACK, type: types.ERASABLE, year: 2024, image: "erasable-bee.webp", legamiId: "EP0029" },
    { id: "E003", character: characters.BUNNY_1, color: colors.PURPLE, type: types.ERASABLE, year: 2022, image: "erasable-bunny.webp", legamiId: "EP0011" },
    { id: "E004", character: characters.DINO, color: colors.GREEN, type: types.ERASABLE, image: "erasable-dino.webp", legamiId: ["EP0007", "EP0065"] },
    { id: "E005", character: characters.HIPPO, color: colors.BLUE, type: types.ERASABLE, year: 2024, image: "erasable-hippo.webp", legamiId: ["EP0028", "EP0068"] },
    { id: "E006", character: characters.KITTY, color: colors.BLACK, type: types.ERASABLE, image: "erasable-kitty.webp", legamiId: "EP0005" },
    { id: "E007", character: characters.LADYBUG, color: colors.RED, type: types.ERASABLE, year: 2026, image: "erasable-ladybug.webp", legamiId: "EP0074" },
    { id: "E008", character: characters.LLAMA, color: colors.BLUE, type: types.ERASABLE, image: "erasable-llama.webp", legamiId: "EP0010" },
    { id: "E009", character: characters.MONSTER, color: colors.BLUE, type: types.ERASABLE, year: 2025, image: "erasable-monster.webp", legamiId: "EP0056" },
    { id: "E010", character: characters.TEDDY, color: colors.RED, type: types.ERASABLE, year: 2023, image: "erasable-teddy.webp", legamiId: "EP0024" },
    { id: "E011", character: characters.TIGER, color: colors.ORANGE, type: types.ERASABLE, year: 2025, image: "erasable-tiger.webp", legamiId: "EP0044" },
    { id: "E012", character: characters.UNICORN, color: colors.PINK, type: types.ERASABLE, year: 2022, image: "erasable-unicorn.webp", legamiId: "EP0013" },
    { id: "E013", character: characters.BUTTERFLY, color: colors.PINK, type: types.ERASABLE, year: 2025, image: "erasable-butterfly.webp", legamiId: "EP0045" },
    { id: "E014", character: characters.PENGUIN, color: colors.TURQUOISE, type: types.ERASABLE, year: 2024, image: "erasable-penguin.webp", legamiId: "EP0033" },
    { id: "E015", character: characters.SHARK, color: colors.BLUE, type: types.ERASABLE, year: 2023, image: "erasable-shark.webp", legamiId: "EP0006" },
    { id: "E016", character: characters.CORGI, color: colors.BLACK, type: types.ERASABLE, year: 2023, image: "erasable-corgi.png", note: "Exclusive to Ryman", legamiId: "EP0020" },

    // 2026
    { id: "E065", character: characters.GOLDEN_RETRIEVER, color: colors.RED, type: types.ERASABLE, multipack: multipacks.FUREVER_FRIENDS, image: "erasable-retriever.jpg" },
    { id: "E066", character: characters.BULLDOG, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.FUREVER_FRIENDS, image: "erasable-bulldog.jpg" },
    { id: "E067", character: characters.POODLE, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.FUREVER_FRIENDS, image: "erasable-poodle.jpg" },
    { id: "E017", character: characters.BIRD_YELLOW_BLUE_PURPLE, color: colors.TURQUOISE, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_1, image: "erasable-bird1.webp" },
    { id: "E018", character: characters.BIRD_ORANGE_GREEN_YELLOW, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_1, image: "erasable-bird2.jpeg" },

    // 2025
    { id: "E019", character: characters.NUTCRACKER, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.NUTCRACKER, image: "erasable-nut1.webp", legamiId: "EP0057" },
    { id: "E020", character: characters.BALLERINA, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.NUTCRACKER, image: "erasable-nut2.webp", legamiId: "EP0058" },
    { id: "E021", character: characters.MOUSE, color: colors.RED, type: types.ERASABLE, multipack: multipacks.NUTCRACKER, image: "erasable-nut3.webp", legamiId: "EP0059" },
    { id: "E022", character: characters.BEAR, color: colors.RED, type: types.ERASABLE, event: events.CHRISTMAS, year: 2025, notes: "Advent calendar", image: "erasable-train.avif" },
    { id: "E023", character: characters.ZOMBIE, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1, image: "erasable-zombi.jpg", legamiId: "EP0053" },
    { id: "E024", character: characters.HALLOWEEN_CAT, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1, image: "erasable-halloweencat.jpg", legamiId: "EP0054" },
    { id: "E025", character: characters.HALLOWEEN_SKELETON, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_1, image: "erasable-skeleton.jpg", legamiId: "EP0055" },
    { id: "E026", character: characters.COW, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.FARM, image: "erasable-cow.webp", legamiId: "EP0048" },
    { id: "E027", character: characters.PIGLET, color: colors.PINK, type: types.ERASABLE, multipack: multipacks.FARM, image: "erasable-piglet.webp", legamiId: "EP0049" },
    { id: "E028", character: characters.DONKEY, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.FARM, image: "erasable-donkey.webp", legamiId: "EP0050" },
    { id: "E029", character: characters.ROOSTER, color: colors.RED, type: types.ERASABLE, multipack: multipacks.FARM, image: "erasable-rooster.webp", legamiId: "EP0051" },
    { id: "E030", character: characters.EASTER_BUNNY, color: colors.PINK, type: types.ERASABLE, multipack: multipacks.HOPPY_EASTER_2, image: "erasable-easterbunny.jpg", legamiId: "EP0046" },
    { id: "E031", character: characters.EASTER_CHICK, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.HOPPY_EASTER_2, image: "erasable-easterchick.jpg", legamiId: "EP0047" },

    // 2024
    { id: "E032", character: characters.ELF, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE, image: "erasable-elf.webp", legamiId: "EP0039" },
    { id: "E033", character: characters.REINDEER, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE, image: "erasable-reindeer.jpg", legamiId: "EP0038" },
    { id: "E034", character: characters.SANTA, color: colors.RED, type: types.ERASABLE, multipack: multipacks.NAUGHTY_OR_NICE, image: "erasable-santa.webp", legamiId: "EP0037" },
    { id: "E035", character: characters.SANTA, color: colors.BLACK, type: types.ERASABLE, event: events.CHRISTMAS, year: 2024, notes: "Blue pen, available separately to the Naughty or Nice multipack", image: "erasable-santablue.png", legamiId: "EP0041" },
    { id: "E036", character: characters.YETI, color: colors.BLUE, type: types.ERASABLE, event: events.CHRISTMAS, year: 2024, notes: "Advent calendar", image: "erasable-yeti.png" },
    { id: "E037", character: characters.BAT, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2, image: "erasable-bat.jpg", legamiId: "EP0034" },
    { id: "E038", character: characters.WITCH, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2, image: "erasable-witch.jpg", legamiId: "EP0035" },
    { id: "E039", character: characters.VAMPIRE, color: colors.RED, type: types.ERASABLE, multipack: multipacks.BOO_CREW_2, image: "erasable-vampire.jpg", legamiId: "EP0036" },
    { id: "E065", character: characters.BAT2, color: colors.BLACK, type: types.ERASABLE, event: events.HALLOWEEN, year: 2024, notes: "Red slogan, available separately to the Boo Crew multipack", image: "erasable-bat2.png" },
    { id: "E040", character: characters.TURTLE, color: colors.TURQUOISE, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA, image: "erasable-turtle.jpg", legamiId: "EP0030" },
    { id: "E041", character: characters.CLOWN_FISH, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA, image: "erasable-clownfish.jpg", legamiId: "EP0031" },
    { id: "E042", character: characters.SEAHORSE, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.UNDER_THE_SEA, image: "erasable-seahorse.jpg", legamiId: "EP0032" },
    { id: "E043", character: characters.CAT_WITH_WOOL, color: colors.RED, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_2, image: "erasable-tabby.jpg" },
    { id: "E044", character: characters.DOG, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BETTER_TOGETHER_2, image: "erasable-dog.jpg" },

    // 2023
    { id: "E045", character: characters.PENGUIN_CHRISTMAS, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2023, image: "erasable-christmaspenguin.jpg", legamiId: "EP0023" },
    { id: "E046", character: characters.FOX_CHRISTMAS, color: colors.GREEN, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2023, image: "erasable-fox.jpg", legamiId: "EP0021" },
    { id: "E047", character: characters.POLAR_BEAR_CHRISTMAS, color: colors.RED, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2023, image: "erasable-polarbear.jpg", legamiId: "EP0022" },
    { id: "E048", character: characters.FRANKENSTEINS_MONSTER, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3, image: "erasable-frank.avif" },
    { id: "E049", character: characters.MUMMY, color: colors.PURPLE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3, image: "erasable-mummy.jpg" },
    { id: "E050", character: characters.PUMPKIN, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.BOO_CREW_3, image: "erasable-pumpkin.jpg" },
    { id: "E051", character: characters.LION_2, color: colors.ORANGE, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH, image: "erasable-lion.jpg", legamiId: "EP0017" },
    { id: "E052", character: characters.ELEPHANT, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH, image: "erasable-elephant.jpg", legamiId: "EP0018" },
    { id: "E053", character: characters.GIRAFFE, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.WILD_SAVANNAH, individual: true, image: "erasable-giraffe.webp", legamiId: "EP0019" },

    // 2022
    { id: "E054", character: characters.KOALA_CHRISTMAS, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2022, image: "erasable-christmasjoala.jpg" },
    { id: "E055", character: characters.BEAR_CHRISTMAS, color: colors.RED, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2022, image: "erasable-christmasbear.jpg" },
    { id: "E056", character: characters.PANDA_CHRISTMAS, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.CHRISTMAS_2022, image: "erasable-christmaspanda.jpg" },

    // Discontinued
    { id: "E057", character: characters.ASTRONAUT, color: colors.BLACK, type: types.ERASABLE, discontinued: 2024, image: "erasable-astronaut.avif", legamiId: "EP0009" },
    { id: "E058", character: characters.FLORA, color: colors.PINK, type: types.ERASABLE, discontinued: 2024, image: "erasable-flora.jpg", legamiId: "EP0012" },
    { id: "E059", character: characters.PIG, color: colors.PINK, type: types.ERASABLE, discontinued: 2024, image: "erasable-pig.webp", legamiId: "EP0008" },
    { id: "E060", character: characters.PANDA, color: colors.BLACK, type: types.ERASABLE, multipack: multipacks.ORIGINAL, individual: true, discontinued: 2024, notes: "Plain white pen", image: "erasable-pandawhite.webp", legamiId: "EP0001" },
    { id: "E061", character: characters.TEDDY, color: colors.BLUE, type: types.ERASABLE, multipack: multipacks.ORIGINAL, individual: true, discontinued: 2024, notes: "Plain bear, no honey pot", image: "erasable-teddyold.webp", legamiId: "EP0002" },
    { id: "E062", character: characters.KOALA_2, color: colors.RED, type: types.ERASABLE, multipack: multipacks.ORIGINAL, individual: true, discontinued: 2023, image: "erasable-koala.webp", legamiId: "EP0003" },
    { id: "E063", character: characters.SHARK_GRUMPY, color: colors.BLUE, type: types.ERASABLE, discontinued: 2023, image: "erasable-sharkgrumpy.webp", legamiId: "EP0006" },
    { id: "E064", character: characters.UNICORN, color: colors.BLACK, type: types.ERASABLE, discontinued: 2022, notes: "Plain white pen", image: "erasable-unicornwhite.jpg", legamiId: "EP0004" },
]